### ISSUE TITLE
Check whether some content is out of date?

### ISSUE THREAD

**Issue by qdread** [SESYNC-ci/geospatial-packages-in-R-lesson#7]
1. In [extract.Rmd](https://github.com/SESYNC-ci/geospatial-packages-in-R-lesson/blob/master/slides/extract.Rmd), currently we coerce sf objects to sp to make them play with rasters. Is this still necessary?
2. Are any of the resources in [refs.Rmd](https://github.com/SESYNC-ci/geospatial-packages-in-R-lesson/blob/master/slides/refs.Rmd) out of date?

@khondula if you can take a quick look at this it would be great.

**Comment by pmarchand1** [comment]
Hi @qdread,

It's possible to extract from sf directly now. 

Also, in case that's useful, here's a recent ~3h workshop I did on geospatial data:
https://pmarchand1.github.io/atelier_rgeo/rgeo_workshop.html .

While sf does everything for vectors, the raster packages are still a bit confusing. I used stars in my recent workshop because it is closer to the sf and dplyr syntax and interacts well with ggplot2, so it saved some teaching time.

For advanced users, stars supports some non-rectangular data which has niche applications, however it doesn't have all the features of raster for "standard" rasters (missing point extraction, most notably).

Finally, the 'raster' package has a successor 'terra', which should replace it over time but it's just been released so I waited to incorporate it in lessons, instead just mentioning its existence.

**Comment by qdread** [comment]
Thanks @pmarchand1 for the very helpful ideas/resources!

**Comment by khondula** [comment]
Agree with @pmarchand1 that stars is the way to go for now. 

Perhaps consider that it is still handy to show conversion between sf and sp objects given the number of packages built on sp objects? e.g. I think rastervis is still best for some plotting situations. 

Other options to check out or list as resources: [exactextractr](https://isciences.gitlab.io/exactextractr/ ) which is on CRAN, or [velox](https://github.com/hunzikp/velox) however it has since been removed from cran (https://github.com/hunzikp/velox/issues/43)

**Comment by qdread** [comment]
Looks like a way to extract from the raster at a point, if the point is an `sfc_POINT` object, is `extract(Raster, st_coordinates(sfc_POINT))`.

In the long term we should convert all `raster` parts of the lesson to `stars`, if it is the current industry standard. Eventually I am sure that `stars` will support point extraction and not require coercion to `Raster` object. The question is whether to do this in time for the 2020 institute.

**Comment by qdread** [comment]
Commit 073fd49:
I updated the lesson so that we extract from `sf` objects. In the case of the point geometry we just convert the points to a matrix with `st_coordinates()` rather than introducing the `sp` package to the learners. I still mention in the notes that coercion to `sp` may be necessary in some cases when working with `raster`. I also updated the description of the status of the `stars` package.

Leaving the issue open to remind us to eventually replace the creakingly old raster package with stars and/or terra in future versions of the lesson.

**Comment by qdread** [comment]
Update: the `terra` package has now progressed to the point where we can replace `raster` with `terra`. (Robert Hijmans just made some changes so that the NLCD raster can be read in and preserve the factor levels). I will update this lesson to work with `terra`.

**Comment by qdread** [comment]
You can see in 01cb036 on the `use-terra` branch that I was able to update everything in the `raster.Rmd` part of the lesson but `extract.Rmd` not yet because the `terra::extract()` fn does not support extracting from sf objects. Yes, you could coerce it to a different class, but I think there's no point in doing that. It would complicate things so there is no point in switching from `raster` to `terra` until we can do things just as simply in `terra` as we can in `raster`.

**Comment by qdread** [comment]
This is superseded now by #9 and the discussion is basically irrelevant so closing
